'use strict';

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fc = require('fast-check');
const { parseSteeringDoc, printSteeringDoc, formatSteeringForPrompt } = require('../steering-loader.js');

// --- Generators ---

/**
 * Generate a simple alphanumeric string with spaces, avoiding characters
 * that break YAML parsing (colons, newlines, dashes at start).
 */
function arbitrarySafeString() {
  return fc
    .stringMatching(/^[a-zA-Z][a-zA-Z0-9 ]{0,29}$/)
    .map((s) => s.trim())
    .filter((s) => s.length > 0);
}

/**
 * Generate a random markdown body string (alphanumeric with spaces and newlines).
 */
function arbitraryBody() {
  return fc
    .stringMatching(/^[a-zA-Z0-9 \n#*-]{0,80}$/);
}

// --- Property Tests ---

describe('Property-based tests for steering-doc.js', () => {
  // 5.4 Property 7: Steering doc serialization round-trip
  // **Validates: Requirements 6.4**
  it('Property 7: Steering doc serialization round-trip', () => {
    fc.assert(
      fc.property(
        arbitrarySafeString(),
        arbitrarySafeString(),
        fc.boolean(),
        arbitraryBody(),
        (name, description, autoGenerated, body) => {
          const frontMatter = {
            name,
            description,
            auto_generated: autoGenerated,
          };

          // Serialize then parse back
          const serialized = printSteeringDoc(frontMatter, body);
          const parsed = parseSteeringDoc(serialized);

          // Assert round-trip equivalence
          assert.equal(
            parsed.frontMatter.name,
            name,
            `name should round-trip: expected "${name}", got "${parsed.frontMatter.name}"`
          );
          assert.equal(
            parsed.frontMatter.description,
            description,
            `description should round-trip: expected "${description}", got "${parsed.frontMatter.description}"`
          );
          assert.equal(
            parsed.frontMatter.auto_generated,
            autoGenerated,
            `auto_generated should round-trip: expected ${autoGenerated}, got ${parsed.frontMatter.auto_generated}`
          );
          assert.equal(
            parsed.body,
            body,
            `body should round-trip`
          );
        }
      ),
      { numRuns: 150 }
    );
  });
});

describe('Property-based tests for formatSteeringForPrompt', () => {
  // 5.5 Property 8: Steering doc prompt injection completeness
  // **Validates: Requirements 7.1, 7.2**
  it('Property 8: For any non-empty array of SteeringDoc objects, formatSteeringForPrompt SHALL produce a string that contains every doc name as a sub-header and every doc body content', () => {
    const arbitrarySteeringDoc = fc.record({
      name: arbitrarySafeString(),
      description: arbitrarySafeString(),
      autoGenerated: fc.boolean(),
      body: arbitraryBody(),
    });

    fc.assert(
      fc.property(
        fc.array(arbitrarySteeringDoc, { minLength: 1, maxLength: 10 }),
        (docs) => {
          const result = formatSteeringForPrompt(docs);

          // Must contain the Project Context header
          assert.ok(
            result.includes('## Project Context'),
            'Result should contain "## Project Context" header'
          );

          // For each doc, result must contain its name as a sub-header and its body
          for (const doc of docs) {
            assert.ok(
              result.includes(`### ${doc.name}`),
              `Result should contain sub-header "### ${doc.name}"`
            );
            // formatSteeringForPrompt trims trailing whitespace from the output,
            // so we check that the trimmed body content is present.
            const trimmedBody = doc.body.trim();
            if (trimmedBody.length > 0) {
              assert.ok(
                result.includes(trimmedBody),
                `Result should contain doc body for "${doc.name}"`
              );
            }
          }
        }
      ),
      { numRuns: 150 }
    );
  });
});
